apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.1
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: kc-config
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kc-secret
                  key: keycloak_admin_password
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: kc-config
                  key: KEYCLOAK_DATABASE_URL
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-password
                  key: password
            - name: KEYCLOAK_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: kc-config
                  key: KEYCLOAK_DATABASE_PORT
            - name: DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: kc-config
                  key: KEYCLOAK_DATABASE_NAME
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kc-config
                  key: KEYCLOAK_DATABASE_USER
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080