apiVersion: v1
kind: Pod
metadata:
 name: hook-preinstall
 annotations:
   "helm.sh/hook": "pre-install"
spec:
 containers:
 - name: hook1-container
   image: busybox
   imagePullPolicy: IfNotPresent
   command: [
     'sh',
     '-c',
     'while [[ $(kubectl get pods -n cnpg-system --field-selector=status.phase!=Running 2>&1) ==
     "No resources found in cnpg-system namespace." ]]; do sleep 1; done'
   ]
 restartPolicy: Never
 terminationGracePeriodSeconds: 0
